"""add reset token column

Revision ID: 83665d675915
Revises: 656bb3c0a09d
Create Date: 2020-07-29 15:05:13.552397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83665d675915'
down_revision = '656bb3c0a09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
